#!/bin/bash

cd /tmp/;

#RELEASE=$1

#RELEASE=$(curl -s https://github.com/derailed/k9s/releases/latest | grep -oE '[0-9]{1}.[0-9]{2}.[0-9]{1}')

RELEASE=0.7.1

echo "Updating to version: ${RELEASE}"

URL=https://raw.githubusercontent.com/ahmetb/kubectx/v${RELEASE}/kubectx

echo "Curling URL: $URL"

curl -LOs $URL

BINPATH=/usr/local/bin
echo "Moving kubectx into $BINPATH"
sudo mv kubectx $BINPATH

echo "Making kubectx executable by all $USER"
sudo chown $USER:$USER $BINPATH/kubectx
sudo chmod 0755 $BINPATH/kubectx
#ls -al /usr/local/bin/kubectx

echo "Removing kubectx from /tmp/ directory"
rm kubectx

