#!/bin/bash

cd /tmp/;

#RELEASE=$1

RELEASE=$(curl -s https://github.com/derailed/k9s/releases/latest | grep -oE '[0-9]{1}.[0-9]{2}.[0-9]{1}')

PKG=k9s_${RELEASE}_Linux_x86_64.tar.gz

echo "Updating to version: ${RELEASE}"

URL=https://github.com/derailed/k9s/releases/download/v$RELEASE/$PKG

echo "Curling URL: $URL"

curl -LOs $URL

echo "Unpacking $PKG"
tar --extract -f $PKG k9s

K9PATH=/usr/local/bin
echo "Moving k9s into $K9PATH"
sudo mv k9s $K9PATH

echo "Making k9s executable by all $USER"
sudo chown $USER:$USER $K9PATH/k9s
sudo chmod 0755 $K9PATH/k9s
#ls -al /usr/local/bin/k9s

echo "Removing $PKG from /tmp/ directory"
rm -r $PKG
